name: Generate dev documentation

on:
  push:
    branches:
      - dev

jobs:
  build_docs:
    name: Generate dev documentation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]
        ruby-version: [ 3.0 ]
        node-version: [ 16.x ]
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/slate/Gemfile
      
    steps:
      - name: Checkout source files
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
          
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}   
          cache: 'npm'          
                
      - name: Install Widdershins
        run: npm install -g widdershins
        
      - name: Convert swagger to markdown
        run: |
          cd scripts
          sh github-action-json-to-markdown.sh          

      - name: Set up Ruby  ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically on env.BUNDLE_GEMFILE
                      
      - name: Build source with middleman 
        run: |
          cd scripts
          sh github-action-build-slate.sh
          
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64      
          cache: 'pip'          
          cache-dependency-path: 'mkdocs/requirements.txt'
            
      - name: Install Python dependencies
        run: python3 -m pip install -r ./mkdocs/requirements.txt

      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
                
      - name: Deploy MkDoc with mike 🚀
        run: |
          cd mkdocs
          mike deploy --push dev
